export const DEFAULT_COLOR_SCHEME = 'teal'
export const DESCRIPTION = 'NFT fundraiser platform for Ukraine'
export const IMAGE_OG = '/images/logo.jpeg'
export const SITE_URL = 'https://ukrainewartime.art'
export const SOCIAL_HANDLE = '@UkrKidsArt'
export const TITLE = 'Ukraine Wartime Art'
export const TWITTER_URL = 'https://twitter.com/ukrainewar_art';
export const DISCORD_URL = 'https://discord.gg/NsB9bdeU';
export const INSTAGRAM_URL = 'https://www.instagram.com/ukrainewartime.art';