export const DEFAULT_COLOR_SCHEME = 'teal'
export const DESCRIPTION = 'support for Ukraine'
export const IMAGE_OG = '/images/logo.png'
export const SITE_URL = ''
export const SOCIAL_HANDLE = ''
export const TITLE = 'Ukraine Wartime Art'
